autoclose_curlybraces: true
autoclose_doublequotes: true
autoclose_parentheses: true
autoclose_singlequotes: true
autoclose_squarebrackets: true
font_color: '#fbf1c7'
font_family: monospace
font_size: 12
insertion_blink: false
insertion_color: '#75715E'
menu_active_bg: '#282828'
menu_active_fg: '#83a593'
menu_bg: '#1d2021'
tab_size: 4
text_bottom_lineheight: '1'
text_top_lineheight: '1'
text_wrap: none
textarea_background_color: '#282828'
textarea_padding_x: '5'
textarea_padding_y: '5'







