bg_color: '#38342b'
bottom_spacing: '1'
font_family: monospace
font_size: 12
insertion_blink: 'false'
menu_active_bg: '#38342b'
menu_active_fg: '#fff'
menu_bg: '#181816'
padding_x: '5'
padding_y: '5'
tab_size: 4
text_color: white
top_spacing: '1'

