bg_color: '#38342b'
bottom_spacing: '1'
font_color: '#fbf1c7'
font_family: monospace
font_size: 12
insertion_blink: false
insertion_color: '#d5c4a1'
menu_active_bg: '#38342b'
menu_active_fg: '#d5c4a1'
menu_bg: '#181816'
padding_x: '5'
padding_y: '5'
tab_size: 4
top_spacing: '1'
text_wrap: 'none'

